# Generated by Django 3.1 on 2020-08-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200812_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passager',
            new_name='Passenger',
        ),
    ]
